# Schema for the configuration files of the Kimono Theme theme.
kimono_theme.settings:
  type: theme_settings
  label: 'Kimono Theme settings'
  mapping:
    example:
      type: string
      label: Example
